version: '3'

services:
  raven-rwkv-service-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    command: python obsidian_serve.py serve --host=0.0.0.0 --port 8080
    environment:
      - RAY_ADDRESS=ray://ray_server:10001
    ports:
    - 8081:8080
    networks:
      - my_network
    volumes:
    - ./compose.models.toml:/home/user/app/models.toml
      
  raven-rwkv-service-backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RAY_ADDRESS=ray://ray_server:10001
    command: python -m simple_rwkv -a 0.0.0.0:50051
    networks:
      - my_network
    depends_on:
    - model_server

  ray_server:
    build:
      context: .
      dockerfile: Dockerfile
    command: ray start --head --block
    networks:
      - my_network

  model_server:
    build:
      context: .
      dockerfile: Dockerfile
    command: serve run simple_rwkv.ray_server:d
    environment:
      - RAY_ADDRESS=ray://ray_server:10001
    networks:
      - my_network
    depends_on:
    - ray_server

networks:
  my_network:
